### ISSUE TITLE
VSCode probe-rs extension doesn't highlight and/or change coloring of Rust source code line at which breakpoint has triggered

### ISSUE THREAD

**Issue by jerrywrice** [probe-rs/vscode#114]
Using VSCode (version 1.97.2) with probe-rs-debug extension (version 0.24.2) doesn't visually indicate the specific rust source file line of code at which a breakpoint is initially triggered, nor when single-stepping.

**Comment by noppej** [comment]
There are definitely some challenges with breakpoint stepping, but many use cases work as expected. Can you please provide more information so that I can assess if this is a known issue, or something new.  If you can reproduce this using a simple blinky example, that is ideal. If not, perhaps a link to your repo, with instructions for reproducing?
At the very least, I need to know what chip/board you are using, launch.json, tasks.json, Cargo.toml, but obviously more info here is better.

**Comment by JustinG002** [comment]
Hello I am facing the same issue as well, here is my set up below:

MCU:
STM32C031k6tx 

Debugger:
SLogic8 - DAPLink

Project:
Default project generated with [stm32-template](https://github.com/burrbull/stm32-template). The following config are used:
- The STM32C0xx hal library is broken, so it's removed from compilation
- It's not a RTIC base application
- It does not use defmt logger
- MCU name is stm32c031k6tx

You can review the `launch.json`, `tasks.json`, `Cargo.toml` of the generated project, only `Cargo.toml` is modified as below:
``` toml
[package]
name = "thing"
version = "0.1.0"
authors = ["Justin_Gong <justingong002@gmail.c>"]
edition = "2021"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-halt = "0.2.0"


# [dependencies.stm32c0xx-hal]
# git = "https://github.com/stm32-rs/stm32c0xx-hal"
# features = ["stm32c031", ]

[build-dependencies]
reqwest = { version = "0.11", features = ["blocking"] }

# Set the default for dependencies.
[profile.dev.package."*"]
opt-level = 0

[profile.release]
codegen-units = 1
incremental = false
debug = true
lto = true
opt-level = "s"

```

When running debugging using probe-rs-debugger with debug option selected, the line number of break point is correct but line number is not selected and file is labelled Unknown Source. I was able to verify with a blinky that the program was uploaded and the program is halted. 

Using `cargo embed` with `GDB` can properly shows the "break pointed" line and which file.

![Image](https://github.com/user-attachments/assets/302e9e28-d75a-4677-b819-16ecce46d486)

Happy to provide more info as needed.
