### ISSUE TITLE
Couple of probably related issues - unable to reset nrf52840-mdk 

### ISSUE THREAD

**Issue by nihalpasham** [probe-rs/vscode#8]
When attempting to debug, `vscode probe-rs-debug` doesnt `halt on reset` and I believe it actually picks up state from the previous session (cant confirm though). Upon trying to manually attempt a reset, the session drops out. In other words, cant seem to start a fresh debugging session. 
 
board: [nrf52840-mdk (maker diary)](https://makerdiary.com/collections/frontpage/products/nrf52840-mdk-iot-development-kit)

These are the contents of my `launch.json`.
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "preLaunchTask": "${defaultBuildTask}",
            "type": "probe-rs-debug",
            "request": "launch",
            "name": "rustBoot launch",
            "program_binary": "${workspaceFolder}/boards/target/thumbv7em-none-eabihf/release/nrf52840",
            "chip": "nRF52840_xxAA",
            "connect_under_reset": false,
            "speed": 24000,
            "runtimeExecutable": "probe-rs-debugger",
            "runtimeArgs": [
                "debug",
                "--dap"
            ],
            "core_index": 0,
            "flashing_enabled": true,
            "reset_after_flashing": true,
            "halt_after_reset": true,
            "console_log_level": "Info",
            // "svdFile": "${workspaceRoot}/nrf52840.svd"
        },
        {
            "type": "probe-rs-debug",
            "request": "attach",
            "name": "rustBoot attach",
            "server": "127.0.0.1:50001",
            "cwd": "${workspaceFolder}",
            "program_binary": "${workspaceFolder}/boards/target/thumbv7em-none-eabihf/release/nrf52840",
            "chip": "nRF52840_xxAA",
            "connect_under_reset": false,
            "speed": 24000,
            "core_index": 0,
            "flashing_enabled": false,
            "reset_after_flashing": false,
            "halt_after_reset": true,
            "console_log_level": "Info"
        }
    ]
}
```

There are a couple of other accompanying issues which I believe may be related to this. (have screenshots for these problems, if you need them).
- Errors in extracting the location of `local variables`
- Error when unwrapping any kind of option. (cant find file)
- Cant seem to get `defmt` logs out. (defmt macros and rtt is enabled)

I'm not entirely sure if this is due to it being an alpha build or if something's wrong with my set-up.

**Comment by noppej** [comment]
Hi Nihal,

I will try my best to get you going, but need a bit more info first ...

> When attempting to debug, `vscode probe-rs-debug` doesnt `halt on reset` and I believe it actually picks up state from the previous session (cant confirm though). Upon trying to manually attempt a reset, the session drops out. In other words, cant seem to start a fresh debugging session. 
>
Are you referring to expecting a `halt on reset` when you manually reset? That is not something we have tested and I would not expect it to work. There is an Issue logged to improve this, but we have not actioned it yet. If you are referring to expecting a `halt on reset` after the flashing, then we need to dig into that, as it may be a problem with either the code or the config. Please clarify :) 
 
> There are a couple of other accompanying issues which I believe may be related to this. (have screenshots for these problems, if you need them).
> 
> - Errors in extracting the location of `local variables`
> 
> - Error when unwrapping any kind of option. (cant find file)
> 
>
Can you please send me the .cargo/config file as well as the Cargo.toml file you are using? 

> - Cant seem to get `defmt` logs out. (defmt macros and rtt is enabled)
>
The current posted release does not support RTT. There is a WIP Pull Request where it mostly works, but I suggest you wait a week or so until we have it fully tested and merged before you try that.

**Comment by nihalpasham** [comment]
> Are you referring to expecting a `halt on reset` when you manually reset? That is not something we have tested and I would not expect it to work. There is an Issue logged to improve this, but we have not actioned it yet. If you are referring to expecting a `halt on reset` after the flashing, then we need to dig into that, as it may be a problem with either the code or the config. Please clarify :)
- `halt on reset after flashing:` works but not always i.e. in some instances, it goes into an `undefined state`. (on more than one occasion I noticed it landed in some exception that must have been triggered by part of the code I'm trying to debug or possibly some previous state.)
- `manual halt on reset:`  - yep, can confirm this does not work.

> Can you please send me the .cargo/config file as well as the Cargo.toml file you are using?

**config.toml:** 
```toml
[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip nRF52840_xxAA"
rustflags = [
  "-C", "linker=flip-link",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
  # This is needed if your flash or ram addresses are not aligned to 0x10000 in memory.x
  # See https://github.com/rust-embedded/cortex-m-quickstart/pull/95
  "-C", "link-arg=--nmagic",
]

[build]
target = "thumbv7em-none-eabihf"
```

**Cargo.toml: workspace**
```toml
[workspace]

members = ["rustBoot-update",
           "rustBoot-hal", 
           "test_firmware/*/*", 
           "test_impls/*"
           ]

[profile.dev]
incremental = false
codegen-units = 1
debug = true
lto = false

[profile.release]
debug = true
lto = true
opt-level = "s"
panic = "abort"
```
**Cargo.toml: project**
```toml 
[package]
build = "build.rs"
edition = "2018"
name = "nrf52840"
version = "0.1.0"

# makes `cargo check --all-targets` work
[[bin]]
bench = false
doctest = false
name = "nrf52840"
test = false

[dependencies]
cortex-m-rt = "0.6.15"
defmt = "0.2.3"
defmt-rtt = {version = "0.2.0"}
panic-probe = {version = "0.2.0", features = ["print-defmt"]}
rustBoot-hal = {path = "../../rustBoot-hal", default-features = false, features = ["nrf52840"]}
rustBoot-update = {path = "../../rustBoot-update"}

[features]
default = ['defmt-default']
# these features are required by defmt
defmt-debug = []
defmt-default = []
defmt-error = []
defmt-info = []
defmt-trace = []
defmt-warn = []

# [workspace]
```
> The current posted release does not support RTT. There is a WIP Pull Request where it mostly works, but I suggest you wait a week or so until we have it fully tested and merged before you try that.

Noted. cool.
